drop table
if exists
DEMO_STATES
cascade
;

drop table
if exists
clibanque
cascade
;

drop table
if exists
EMP
cascade
;

drop table
if exists
stats
cascade
;

drop table
if exists
DEMO_CUSTOMERS
cascade
;

drop table
if exists
CUSTNAMES
cascade
;


CREATE TABLE DEMO_STATES(	
	ST VARCHAR PRIMARY KEY, 
	STATE_NAME VARCHAR
);

create table clibanque(
	idCli INT,
	nomCli VARCHAR(50),
	idConjoint INT,
	constraint cliPK primary key(idCli),
	constraint cliFK foreign key(idConjoint) references clibanque(idCli)
);

CREATE TABLE EMP (
	EMPNO NUMERIC(4) PRIMARY KEY, 
	ENAME VARCHAR(10), 
	JOB VARCHAR(9), 
	MGR NUMERIC(4), 
	HIREDATE DATE, 
	SAL NUMERIC(6,2), 
	COMM NUMERIC(6,2), 
	DEPTNO NUMERIC(2)
);

CREATE TABLE stats(
	typeMaj CHAR(6) PRIMARY KEY,
	nbMaj BIGINT,
	timestampModif TIMESTAMP
);

CREATE TABLE DEMO_CUSTOMERS (
	CUSTOMER_ID NUMERIC PRIMARY KEY, 
	CUST_FIRST_NAME VARCHAR, 
	CUST_LAST_NAME VARCHAR, 
	CUST_STREET_ADDRESS1 VARCHAR, 
	CUST_STREET_ADDRESS2 VARCHAR, 
	CUST_CITY VARCHAR, 
	CUST_STATE VARCHAR, 
	CUST_POSTAL_CODE VARCHAR, 
	PHONE_NUMBER1 VARCHAR, 
	PHONE_NUMBER2 VARCHAR, 
	CREDIT_LIMIT NUMERIC(8,2), 
	CUST_EMAIL VARCHAR
);

CREATE TABLE CUSTNAMES AS
SELECT
	CUSTOMER_ID,
	CUST_FIRST_NAME,
	CUST_LAST_NAME
FROM DEMO_CUSTOMERS
;

  
INSERT INTO DEMO_STATES VALUES (	'AK','ALASKA'	);
INSERT INTO DEMO_STATES VALUES (	'AL','ALABAMA'	);
INSERT INTO DEMO_STATES VALUES (	'AR','ARKANSAS'	);
INSERT INTO DEMO_STATES VALUES (	'AZ','ARIZONA'	);
INSERT INTO DEMO_STATES VALUES (	'CA','CALIFORNIA'	);
INSERT INTO DEMO_STATES VALUES (	'CO','COLORADO'	);
INSERT INTO DEMO_STATES VALUES (	'CT','CONNECTICUT'	);
INSERT INTO DEMO_STATES VALUES (	'DC','DISTRICT OF COLUMBIA'	);
INSERT INTO DEMO_STATES VALUES (	'DE','DELAWARE'	);
INSERT INTO DEMO_STATES VALUES (	'FL','FLORIDA'	);
INSERT INTO DEMO_STATES VALUES (	'GA','GEORGIA'	);
INSERT INTO DEMO_STATES VALUES (	'HI','HAWAII'	);
INSERT INTO DEMO_STATES VALUES (	'IA','IOWA'	);
INSERT INTO DEMO_STATES VALUES (	'ID','IDAHO'	);
INSERT INTO DEMO_STATES VALUES (	'IL','ILLINOIS'	);
INSERT INTO DEMO_STATES VALUES (	'IN','INDIANA'	);
INSERT INTO DEMO_STATES VALUES (	'KS','KANSAS'	);
INSERT INTO DEMO_STATES VALUES (	'KY','KENTUCKY'	);
INSERT INTO DEMO_STATES VALUES (	'LA','LOUISIANA'	);
INSERT INTO DEMO_STATES VALUES (	'MA','MASSACHUSETTS'	);
INSERT INTO DEMO_STATES VALUES (	'MD','MARYLAND'	);
INSERT INTO DEMO_STATES VALUES (	'ME','MAINE'	);
INSERT INTO DEMO_STATES VALUES (	'MI','MICHIGAN'	);
INSERT INTO DEMO_STATES VALUES (	'MN','MINNESOTA'	);
INSERT INTO DEMO_STATES VALUES (	'MO','MISSOURI'	);
INSERT INTO DEMO_STATES VALUES (	'MS','MISSISSIPPI'	);
INSERT INTO DEMO_STATES VALUES (	'MT','MONTANA'	);
INSERT INTO DEMO_STATES VALUES (	'NC','NORTH CAROLINA'	);
INSERT INTO DEMO_STATES VALUES (	'ND','NORTH DAKOTA'	);
INSERT INTO DEMO_STATES VALUES (	'NE','NEBRASKA'	);
INSERT INTO DEMO_STATES VALUES (	'NH','NEW HAMPSHIRE'	);
INSERT INTO DEMO_STATES VALUES (	'NJ','NEW JERSEY'	);
INSERT INTO DEMO_STATES VALUES (	'NM','NEW MEXICO'	);
INSERT INTO DEMO_STATES VALUES (	'NV','NEVADA'	);
INSERT INTO DEMO_STATES VALUES (	'NY','NEW YORK'	);
INSERT INTO DEMO_STATES VALUES (	'OH','OHIO'	);
INSERT INTO DEMO_STATES VALUES (	'OK','OKLAHOMA'	);
INSERT INTO DEMO_STATES VALUES (	'OR','OREGON'	);
INSERT INTO DEMO_STATES VALUES (	'PA','PENNSYLVANIA'	);
INSERT INTO DEMO_STATES VALUES (	'RI','RHODE ISLAND'	);
INSERT INTO DEMO_STATES VALUES (	'SC','SOUTH CAROLINA'	);
INSERT INTO DEMO_STATES VALUES (	'SD','SOUTH DAKOTA'	);
INSERT INTO DEMO_STATES VALUES (	'TN','TENNESSEE'	);
INSERT INTO DEMO_STATES VALUES (	'TX','TEXAS'	);
INSERT INTO DEMO_STATES VALUES (	'UT','UTAH'	);
INSERT INTO DEMO_STATES VALUES (	'VA','VIRGINIA'	);
INSERT INTO DEMO_STATES VALUES (	'VT','VERMONT'	);
INSERT INTO DEMO_STATES VALUES (	'WA','WASHINGTON'	);
INSERT INTO DEMO_STATES VALUES (	'WI','WISCONSIN'	);
INSERT INTO DEMO_STATES VALUES (	'WV','WEST VIRGINIA'	);
INSERT INTO DEMO_STATES VALUES (	'WY','WYOMING'	);

INSERT INTO EMP VALUES(7369, 'SMITH',  'CLERK', 	7902, '17-dec-1980',	 800,	NULL,	20);
INSERT INTO EMP VALUES(7499, 'ALLEN',  'SALESMAN', 	7698, '20-feb-1981',	1600,	 300,	30);
INSERT INTO EMP VALUES(7521, 'WARD',   'SALESMAN', 	7698, '22-feb-1981',	1250,	 500,	30);
INSERT INTO EMP VALUES(7566, 'JONES',  'MANAGER', 	7839, '02-apr-1981',	2975,	NULL,	20);
INSERT INTO EMP VALUES(7654, 'MARTIN', 'SALESMAN', 	7698, '28-sep-1981',	1250,	1400,	30);
INSERT INTO EMP VALUES(7698, 'BLAKE',  'MANAGER', 	7839, '01-may-1981',	2850,	NULL,	30);
INSERT INTO EMP VALUES(7782, 'CLARK',  'MANAGER', 	7839, '09-jun-1981',	2450,	NULL,	10);
INSERT INTO EMP VALUES(7839, 'KING',   'PRESIDENT', NULL, '17-nov-1981',	5000,	NULL,	10);
INSERT INTO EMP VALUES(7844, 'TURNER', 'SALESMAN', 	7698, '08-sep-1981',	1500,	   0,	30);
INSERT INTO EMP VALUES(7900, 'JAMES',  'CLERK', 	7698, '03-dec-1981',	 950,	NULL,	30);
INSERT INTO EMP VALUES(7902, 'FORD',   'ANALYST', 	7566, '03-dec-1981',	3000,	NULL,	20);
INSERT INTO EMP VALUES(7934, 'MILLER', 'CLERK', 	7782, '23-jan-1982',	1300,	NULL,	10);

INSERT INTO stats VALUES('INSERT', 0, NULL);
INSERT INTO stats VALUES('UPDATE', 0, NULL);
INSERT INTO stats VALUES('DELETE', 0, NULL);

INSERT INTO DEMO_CUSTOMERS VALUES (	1,'John','Dulles','45020 Aviation Drive','','Sterling','VA','20166','703-555-2143','','1000',''	);
INSERT INTO DEMO_CUSTOMERS VALUES (	2,'William','Hartsfield','6000 North Terminal Parkway','','Atlanta','GA','30320','404-555-3285','','1000',''	);
INSERT INTO DEMO_CUSTOMERS VALUES (	3,'Edward','Logan','1 Harborside Drive','','East Boston','MA','02128','617-555-3295','','1000',''	);
INSERT INTO DEMO_CUSTOMERS VALUES (	4,'Edward ''Butch''','OHare','10000 West OHare','','Chicago','IL','60666','773-555-7693','','1000',''	);
INSERT INTO DEMO_CUSTOMERS VALUES (	5,'Fiorello','LaGuardia','Hangar Center','Third Floor','Flushing','NY','11371','212-555-3923','','1000',''	);
INSERT INTO DEMO_CUSTOMERS VALUES (	6,'Albert','Lambert','10701 Lambert International Blvd.','','St. Louis','MO','63145','314-555-4022','','1000',''	);
INSERT INTO DEMO_CUSTOMERS VALUES (	7,'Eugene','Bradley','Schoephoester Road','','Windsor Locks','CT','06096','860-555-1835','','1000',''	);


COMMIT;